CREATE TABLE [dbo].[ItemBorrowDayCounts](
	[ItemBorrowDayCountID] [int] IDENTITY(1,1) NOT NULL,
	[LibraryLocationID] [int] NOT NULL,
	[NumberOfDays] [int] NOT NULL,
 CONSTRAINT [PK_dbo.ItemBorrowDayCounts] PRIMARY KEY CLUSTERED 
(
	[ItemBorrowDayCountID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]