//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualCommunityLibrary.Models.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    public partial class ItemType
    {
        public int ItemTypeID { get; set; }
        public Nullable<int> TypeNameID { get; set; }
        public string TypeDescription { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }

        public ItemTypeName itemTypeName { get; set; }
        public IEnumerable<SelectListItem> ItemTypeNameList { get; set; }
        [NotMapped]
        public virtual List<ItemType> itemTypes { get; set; }
        public ItemTypeName itemTypeNames { get; set; }
    }
}
